### ISSUE TITLE
Not compatible with Python 3.6

### ISSUE THREAD

**Issue by rbtcollins** [DRMacIver/hypothesis#125]
I haven't checked 3.5 yet, but on 3.6:
```
python ./05.py 
Traceback (most recent call last):
  File "./05.py", line 14, in <module>
    from hypothesis import given
  File "/home/robertc/.virtualenvs/effect-3.6/lib/python3.6/site-packages/hypothesis/__init__.py", line 31, in <module>
    from hypothesis.core import given, assume, find, example
  File "/home/robertc/.virtualenvs/effect-3.6/lib/python3.6/site-packages/hypothesis/core.py", line 32, in <module>
    import hypothesis.strategies as sd
  File "/home/robertc/.virtualenvs/effect-3.6/lib/python3.6/site-packages/hypothesis/strategies.py", line 86, in <module>
    @defines_strategy
  File "/home/robertc/.virtualenvs/effect-3.6/lib/python3.6/site-packages/hypothesis/strategies.py", line 52, in defines_strategy
    argspec = inspect.getargspec(strategy_definition)
AttributeError: module 'inspect' has no attribute 'getargspec'
```

**Comment by rbtcollins** [comment]
3.5 looks fine.

**Comment by The-Compiler** [comment]
`inspect.getargspec` was deprecated since 3.0 and apparently removed in 3.6. One alternative is to use `inspect.getfullargspec` instead which simply returns a bigger tuple - but it seems that got deprecated in 3.5, and `inspect.signature` should be used instead.

**Comment by DRMacIver** [comment]
Argh. Thanks for letting me know. I will now proceed to be extremely angry about this release process, but obviously I'll make this work. :-)

My likely workaround is that I will write a shim for getargspec built on top of getfullargspec and ignore the fact that it's deprecated for as long as possible and hope that 2.7 is no longer a thing by the time I have to deal with the next breaking change in the standard library.

**Comment by rbtcollins** [comment]
I'm using funcsigs successfully in mock to support 2.6, 2.7 and 3.2 - https://github.com/testing-cabal/mock/blob/master/requirements.txt#L1

It did need a monkeypatch because the maintainer seems to be awol. Here is how I'm driving it: https://github.com/testing-cabal/mock/blob/master/mock/mock.py#L77

**Comment by rbtcollins** [comment]
Oh, so yeah - 2.7 will be a thing for many a year :/. Sorry.

**Comment by DRMacIver** [comment]
This issue at least is now fixed (Python >= 3.5 will use a compatibility shim for getargspec). I can't promise the Hypothesis will work on Python 3.6, and I'm not going to add it to my CI for now, but I'll try to keep on top of anything else you find.
