### ISSUE TITLE
ImportError: cannot import name BasicStrategy

### ISSUE THREAD

**Issue by benmoran** [DRMacIver/hypothesis#269]
The docs at https://github.com/DRMacIver/hypothesis/blob/master/docs/data.rst suggest an import like:

    from hypothesis.searchstrategy import BasicStrategy

which worked in version 1.6.2 but seems to fail for hypothesis 2.0.

**Comment by DRMacIver** [comment]
Ah, that's an error in the docs which have not been updated to reflect its removal in 2.0. Good catch, thanks.

**Comment by DRMacIver** [comment]
Fixed in fbaa0a58a217e0f0f4efccab293c16dfbd702288
