### ISSUE TITLE
Hypothesis on Python 2.6

### ISSUE THREAD

**Issue by tomato42** [DRMacIver/hypothesis#286]
I've noticed that the new hypothesis-3.0.4 does not work on Python 2.6, see here for example failure:
https://travis-ci.org/tomato42/tlslite-ng/jobs/111504747

```
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/hypothesis/searchstrategy/numbers.py", line 104, in do_draw
    return d.integer_range(data, self.start, self.end)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/hypothesis/internal/conjecture/utils.py", line 56, in integer_range
    bits = gap.bit_length()
AttributeError: 'long' object has no attribute 'bit_length'
```

Would you accept patches to restore support for it?

Unit tests are rather important, having to worry that the tests suddenly stop working on older releases does not make me overly confident in it...

And no, dropping support for Python 2.6 is not possible - even that version requires use of python from EPEL on RHEL-5 and given stuff like CVE-2015-3197, support for this old platform is critical.

**Comment by DRMacIver** [comment]
I don't understand why the fact that other people have commercial support contracts for an end of life version of Python should affect your confidence in Hypothesis. Especially given that the major version was incremented when support was dropped (it was officially dropped in 2.0 and actually dropped in 3.0). Could you elaborate?

I'm perfectly happy to accept patches to keep Python 2.6 working, but unless someone feels inclined to pay for support I don't have any intention of officially supporting it and am unlikely to change that intention. In the meantime, there are perfectly usable old versions of Hypothesis you can use on 2.6.

**Comment by Lukasa** [comment]
FWIW, Nick Coghlan (of Red Hat) has explicitly told me in the past that Python projects should drop support for Python 2.6 unless they get paid for that support. I'm in agreement with him and @DRMacIver.

**Comment by tomato42** [comment]
EPEL is free and is available for CentOS 5, Scientific Linux 5 and RHEL-5, so we're not talking about software that is usable with commercial support only.

My point was that neither CentOS 5 nor TravisCI support for python 2.6 is going away, so dropping support for it in hypothesis puts projects in the unfortunate position of either dropping support for old versions or using technically obsolete versions of hypothesis. Just because of a single package. Something that happened now for the second time in just past year or two.

Because hypothesis doesn't "just work", makes me second guess my decision to depend on it for unit tests.

That being said, I don't expect the newest and shiniest features to be supported everywhere, but I see "ABI" breaks for stuff that works just fine with library as old as 1.10 as disruptive and not bringing any gain.

And while I consider hypothesis to be an awesome project, the day has only so many hours in it, I can't follow development of all libraries I use or depend on (be it directly or indirectly).

**Comment by untitaker** [comment]
RedHat could continue support for Python 1.x, this doesn't mean it is reasonable for library developers to keep supporting that version.

IMO the syntax that 2.6 and 3.3+ have in common is way too small for writing somewhat readable code, and without bending over backwards. As you say, the day has only so many hours.

**Comment by Lukasa** [comment]
@tomato42 By that logic, Python 2.6 should be continuing to ship new Python 2.6 releases. Just because Red Hat is supporting 5 year old operating systems with 5 year old software on it does not mean the community at large should do so. If Red Hat would like Hypothesis to continue supporting Python 2.6, they should consider contacting @DRMacIver and offering to pay him for that support, or they should support it themselves.

However, expecting @DRMacIver to do unpaid work to continue to support a version of Python that is EOL from its original distributor is unfair. Python 2.6 is *dead*, by any reasonable measure, with the last release of 2.6 in any form coming at the end of 2013. We cannot require that the Python community continue to support a version of Python released in 2013 just because RHEL 5 does, *especially* as RHEL 5 won't die until at least 2026!

**Comment by untitaker** [comment]
Also, let's not forget:

>I'm perfectly happy to accept patches to keep Python 2.6 working

**Comment by tomato42** [comment]
First EPEL in not provided or supported by Red Hat, it's part of the Fedora project. The only supported version of Python on RHEL-5 is Python 2.4.

Secondly RHEL 5 will "die" earlier - in the beginning of 2017 to be more precise. 2026 is the date for extended support. When RHEL enters extended support EPEL won't be provided for it for much longer. Just as there is no EPEL for RHEL-4.

but that is beside the point, as @DRMacIver agreed not to reject them only on the basis of them adding support for 2.6

I'll try to prepare patches for 2.6 compatibility in the next week or two

**Comment by DRMacIver** [comment]
Note that while I did say I will accept patches to fix 2.6 support, I will *not* accept patches to add 2.6 to CI. My official recommendation remains to not run Hypothesis on 2.6 as it will probably break in patch releases.
